import { REACT_APP_FIREBASE_APIKEY } from "@env"
import { REACT_APP_FIREBASE_MESSAGINGSENDERID } from "@env"
import { REACT_APP_FIREBASE_APPID } from "@env"
import { REACT_APP_FIREBASE_MEASUREMENTId } from "@env"

export default {
    REACT_APP_FIREBASE_APIKEY,
    REACT_APP_FIREBASE_MESSAGINGSENDERID,
    REACT_APP_FIREBASE_APPID,
    REACT_APP_FIREBASE_MEASUREMENTId
};